;PRINTING HELLO WORLD
.MODEL SMALL
.STACK 100H
.DATA

    MSG1 DB 'HELLO!$'
    MSG2 DB 0DH,0AH,'WORLD!$' ;PRINTING WORLD IN NEXT LINE 
    
.CODE
MAIN PROC
    
    MOV AX,@DATA;LOADS OFFSET NUM IN AX REGISTER 
    MOV DS,AX
    
    MOV AH,9;FOR WORKING WITH STRING 
    LEA DX,MSG1
    INT 21H
    
    
    MOV AH,9
    LEA DX,MSG2
    INT 21H
    
    
    MOV AH,4CH;RETURNS VALUE
    INT 21H
    
    MAIN ENDP
END MAIN